### ISSUE TITLE
R_AVR_7_PCREL when linking, seems related to BRNE code emitted?

### ISSUE THREAD

**Issue by carlos4242** [avr-rust/rust#55] opened 2017-05-14 00:16 UTC
The attached file simple.swift is compiled to LLVM bytecode simple.ll and assembly simple.o.s.

It fails when run through the linker (avr-gcc/avr-ld) with the above error.

Investigating, the problem seems to be around here (for example)...

```
  d4:	34 17       	cp	r19, r20
  d6:	41 e0       	ldi	r20, 0x01	; 1
  d8:	01 f4       	brne	.+0      	; 0xda <LBB0_7+0x6>
  da:	40 e0       	ldi	r20, 0x00	; 0
  dc:	00 c0       	rjmp	.+0      	; 0xde <LBB0_10>
```

When the linker tries to hook up the brne, that's a jump back to the start of the main() routine but in this case the main routine is more than 128 bytes (64 words) long, so BRNE cannot jump that far.

This is starting to show up in larger functions, if bits are removed it links fine.

The problem is how to solve this, the code needs to be smart enough to detect in this case the jump will be too far and turn it into a combination of BRNE and some RJMP instructions.

[simple.ll.txt](https://github.com/avr-rust/rust/files/999009/simple.ll.txt)
[simple.o.s.txt](https://github.com/avr-rust/rust/files/999010/simple.o.s.txt)
[simple.swift.txt](https://github.com/avr-rust/rust/files/999011/simple.swift.txt)

**Comment by dylanmckay** [comment] 2017-05-14 02:33
I haven't looked into this deeply, but this sounds like a duplicate of #44 

In that case, we are emitting out of range branches, and we should be relaxing them in a separate pass instead.

**Closed** 2017-05-31 06:59 UTC
